# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 23e5c834c3d93176719b8b7a97474dc0f1a1cc7779196236ad522ddda6ccab58f3a4b4c1f5546612658adf854bc51d494456705abf3286d3169a2647ceccd7da

test:
  secret_key_base: 915e79a64a40c56057da8a6a5318fb0975dd274a98ec24992facce3a39744d1eb86a82e4cbadb6752cb123dc5ec7ece99fecc36ce1ece49621d6582e19a4f02f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
